import React from 'react';

function PrivacyPolicyPage() {
    return (
        <div className="container mx-auto text-black p-8">
            <h1 className="text-4xl font-bold text-purple-700">Privacy Policy</h1>
            <p className="text-xl mt-4">
                Updated at 2024-01-30
            </p>
            <p>
                ToClean (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by ToClean.
            </p>
            <p>
                This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, ToClean App. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Definitions and key terms</h2>
            <p>
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
            </p>
            <ul className="list-disc list-inside text-left">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Top Rated Services, 98-100 Chuter Avenue Ramsgate Beach that is responsible for your information under this Privacy Policy.</li>
                <li><strong>Country:</strong> where ToClean or the owners/founders of ToClean are based, in this case is Australia.</li>
                <li><strong>Customer:</strong> refers to the company, organization, or person that signs up to use the ToClean Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit ToClean and use the services.</li>
                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><strong>Personnel:</strong> refers to those individuals who are employed by ToClean or are under contract to perform a service on behalf of one of the parties.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by ToClean as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>Website:</strong> ToClean's site, which can be accessed via this URL.</li>
                <li><strong>You:</strong> a person or entity that is registered with ToClean to use the Services.</li>
            </ul>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">What Information Do We Collect?</h2>
            <p>
                We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
            </p>
            <ul className="list-disc list-inside text-left">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Mailing Addresses</li>
                <li>Job Titles</li>
                <li>Debit/credit card numbers</li>
                <li>Password</li>
            </ul>
            <p>
                We also collect information from mobile devices for a better user experience, although these features are completely optional:
            </p>
            <ul className="list-disc list-inside text-left">
                <li>Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.</li>
                <li>Phonebook (Contacts list): Your contacts list allows the app to be much easier to use by the user, since accessing your contacts from the app makes you save tons of time.</li>
                <li>Camera (Pictures): Granting camera permission allows the user to upload any picture straight from the app, you can safely deny camera permissions for this app.</li>
                <li>Photo Gallery (Pictures): Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this app.</li>
            </ul>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">How Do We Use The Information We Collect?</h2>
            <p>
                Any of the information we collect from you may be used in one of the following ways:
            </p>
            <ul className="list-disc list-inside text-left">
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
            </ul>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">When does ToClean use end user information from third parties?</h2>
            <p>
                ToClean will collect End User Data necessary to provide the ToClean services to our customers.
            </p>
            <p>
                End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">When does ToClean use customer information from third parties?</h2>
            <p>
                We receive some information from third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a ToClean customer, we receive information from a third party that provides automated fraud detection services to ToClean. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Do we share the information we collect with third parties?</h2>
            <p>
                We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
            </p>
            <p>
                We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, email management, storage marketing, credit card processing, customer service, and fulfilling orders for products and services you may purchase through the app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
            </p>
            <p>
                We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the app in a shared location, and type of device used to visit the app. They may aggregate information about our advertising and what you see on the app and then provide auditing, research and reporting for us and our advertisers. We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Where and when is information collected from customers and end users?</h2>
            <p>
                ToClean will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">How Do We Use Your Email Address?</h2>
            <p>
                By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Could my information be transferred to other countries?</h2>
            <p>
                We are incorporated in Australia. Information collected via our app, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Is the information collected through the ToClean Service secure?</h2>
            <p>
                We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes, or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Can I update or correct my information?</h2>
            <p>
                The rights you have to request updates or corrections to the information ToClean collects depend on your relationship with ToClean. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will not have any effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.
            </p>
            <p>
                You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.
            </p>
            <p>
                If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Personnel</h2>
            <p>
                If you are a ToClean worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.
            </p>
            <p>
                You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will not have any effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Sale of Business</h2>
            <p>
                We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of ToClean or any of its Corporate Affiliates (as defined herein), or that portion of ToClean or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Affiliates</h2>
            <p>
                We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with ToClean, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Governing Law</h2>
            <p>
                This Privacy Policy is governed by the laws of Australia without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.
            </p>
            <p>
                The laws of Australia, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. Your use of the app may also be subject to other local, state, national, or international laws.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">By using ToClean or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.</h2>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Your Consent</h2>
            <p>
                We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our app, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
            </p>
            <h2 className="text-2xl text-purple-600 font-bold mt-8">Links to Other Websites</h2>
            <p>
                This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by ToClean. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
            </p>
            <h2 className="text-2xl text-purple-500 font-bold mt-8">Advertising</h2>
            <p>
                This app may contain third party advertisements and links to third party sites. ToClean does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites, and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.
            </p>
            <p>
                Advertising keeps ToClean and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.
            </p>
            <p>
                Third party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by ToClean of the third party sites, goods or services. ToClean takes no responsibility for the content of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.
            </p>
            <h2 className="text-2xl font-bold text-purple-500 mt-8">Cookies for Advertising</h2>
            <p>
                These cookies collect information over time about your online activity on the app and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.
            </p>
            <h2 className="text-2xl text-purple-500 font-bold mt-8">Cookies</h2>
            <p>
                ToClean uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>
            <h2 className="text-2xl text-purple-500 font-bold mt-8">Blocking and disabling cookies and similar technologies</h2>
            <p>
                Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
            </p>
            <h2 className="text-2xl text-purple-500 font-bold mt-8">California Residents</h2>
            <p>
                The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
            </p>
            <p>
                We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:
            </p>
            <ul className="list-disc list-inside text-left">
                <li>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</li>
                <li>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</li>
                <li>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
                <li>Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
            </ul>
            <p>
                If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our email: orgio@toclean.com.au
            </p>
            <p>
                We do not sell the Personal Information of our users.
            </p>
            <p>
                For more information about these rights, please contact us.
            </p>
            <h2 className="text-2xl text-purple-500 font-bold mt-8">Contact Us</h2>
            <p>
                Don't hesitate to contact us if you have any questions.
            </p>
            <ul className="list-disc list-inside text-left">
                <li>Via Email: orgio@toclean.com.au</li>
                <li><a href="www.toclean.com.au/contact-us" target="_blank" rel="noopener noreferrer">Via this Link: www.toclean.com.au</a></li>
            </ul>
        </div>
    );
}

export default PrivacyPolicyPage;
